apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP        # default, optional to specify
  selector:
    app: backend
  ports:
    - name: http
      port: 80           # service port (inside cluster)
      targetPort: 5000   # container port
