apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nodeport-app
  ports:
    - name: http
      port: 80          # service port (inside cluster)
      targetPort: 80    # container port
      nodePort: 30007   # external port (30000–32767)
